name: Publish Stable Release
on:
  push:
    tags:
      - '[0-9]*.[0-9]*'

jobs:
  publish_stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Stable Release
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

