name: Publish Stable Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+"

jobs:
  publish_stable:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.5" # The Go version to download (if necessary) and use.
      - name: Show go version
        run: go version
      - run: ls -l
      - run: ls -l ..
      - name: build binary
        run: make build
      - name: Publish Stable Release
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binary to release
        run: gh release upload ${{ github.ref_name }} main
