name: Publish Stable Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+'

permissions:
  # write permission is required to create a github release
  contents: write
  # write permission is required for autolabeler
  # otherwise, read permission is required at least
  pull-requests: write

jobs:
  publish_stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Stable Release
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          publish: true

